name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build - (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'ubuntu-24.04', 'macos-13', 'macos-15'] 
        # , 'windows-2022']
    steps:
    - uses: actions/checkout@v4

    - name: setup-ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get -y update
        sudo apt-get remove libunwind-*
        sudo apt-get -y install --no-install-recommends libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - name: setup-mac
      if: contains(matrix.os, 'macos')
      run: |
        brew install --cask gstreamer-development
    - name: configire-build
      run: |
        ./autogen.sh
        ./configure
    - name: make
      run: | 
        make
        mkdir -p dist
        cp ./src/.libs/* ./dist
        cd dist
        openssl version -a >> openssl.info
        cat openssl.info

    - name: Archive build results
      uses: actions/upload-artifact@v4
      with:
        name: gst-Qcrypto-${{ matrix.os }}
        path: |
          dist/*
        retention-days: 1
